# Generated by Django 2.2.5 on 2019-11-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_remove_fee_record_truedd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Phone_No',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stud_admn',
            name='Fid',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.PROTECT, to='entry.Fee_Str'),
        ),
    ]
